# Use the specified base image
FROM dingodatabase/dingo-eureka:rocky9-fs AS builder

# Build and install dingo-sdk
RUN cd / && git clone https://github.com/dingodb/dingo-sdk.git && \
    cd dingo-sdk && \
    git submodule sync --recursive && git submodule update --init --recursive && \
    mkdir build && cd build && cmake -DTHIRD_PARTY_INSTALL_PATH=/root/.local/dingo-eureka -DCMAKE_INSTALL_PREFIX=/root/.local/dingo-sdk -DBUILD_SDK_EXAMPLE=OFF  -DBUILD_BENCHMARK=OFF -DBUILD_PYTHON_SDK=OFF -DBUILD_INTEGRATION_TESTS=OFF -DBUILD_UNIT_TESTS=OFF .. && \
    make -j16 && make install 

ENV DINGOSDK_INSTALL_PATH=/root/.local/dingo-sdk
