# Use the specified base image
FROM dingodatabase/dingo-base:rocky9 AS builder

# Create a working directory
WORKDIR /dingo-eureka

# Copy the project files to the working directory
COPY ../../.. .

# Build and install dingo-eureka
RUN mkdir build && cd build && \
    cmake -DINSTALL_PATH=/root/.local/dingo-eureka .. && \
    ulimit -n 65535 && make -j32 -k

# Build and install dingo-sdk
RUN cd / && git clone https://github.com/dingodb/dingo-sdk.git && \
    cd dingo-sdk && \
    git submodule sync --recursive && git submodule update --init --recursive && \
    mkdir build && cd build && cmake -DTHIRD_PARTY_INSTALL_PATH=/root/.local/dingo-eureka -DCMAKE_INSTALL_PREFIX=/root/.local/dingo-sdk .. && \
    make -j16 && make install 

# Final stage
FROM dingodatabase/dingo-base:rocky9

ENV THIRD_PARTY_INSTALL_PATH=/root/.local/dingo-eureka
ENV DINGO_EUREKA_INSTALL_PATH=/root/.local/dingo-eureka
ENV DINGOSDK_INSTALL_PATH=/root/.local/dingo-sdk

# Copy installed files from builder
COPY --from=builder /root/.local/dingo-eureka /root/.local/dingo-eureka
COPY --from=builder /root/.local/dingo-sdk /root/.local/dingo-sdk

