# Use the specified base image
FROM dingodatabase/dingo-base:rocky9 AS builder

# Create a working directory
WORKDIR /dingo-eureka

# Copy the project files to the working directory
COPY . .

# list files in the current directory for debugging
RUN ls -la /dingo-eureka

# Check /dingo-eureka have .git directory, if not, exit with error
RUN if [ ! -d ".git" ]; then echo "Error: .git directory not found in /dingo-eureka." && exit 1; fi

# Build and install
RUN mkdir build && cd build && \
    cmake -DINSTALL_PATH=/root/.local/dingo-eureka -DWITH_LIBRADOS=OFF -DWITH_BOOST=ON -DWITH_AWSSDKCPP=OFF -DWITH_LIBFUSE=OFF \
    -DWITH_LIBUSRBIO=OFF -DWITH_RDMACORE=OFF -DWITH_TIKVCPP=OFF -DWITH_TIKVGO=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo .. && \
    ulimit -n 65535 && make -j $(nproc)

# Final stage
FROM dingodatabase/dingo-base:rocky9

ENV THIRD_PARTY_INSTALL_PATH=/root/.local/dingo-eureka
ENV DINGO_EUREKA_INSTALL_PATH=/root/.local/dingo-eureka

# Copy installed files from builder
COPY --from=builder /root/.local/dingo-eureka /root/.local/dingo-eureka