name: CI Build

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Record event type
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          echo "EVENT_TYPE=PR" >> $GITHUB_ENV
        elif [ "${{ github.event_name }}" == "push" ]; then
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            echo "EVENT_TYPE=TAG" >> $GITHUB_ENV
            tagInfo=$(echo "${{ github.ref }}" | sed 's/refs\/tags\///')
            if [ -n "$tagInfo" ]; then
              echo "TAG_NAME=$tagInfo" >> $GITHUB_ENV 
            fi
          else
            echo "EVENT_TYPE=PUSH" >> $GITHUB_ENV
          fi
        fi

    - name: Copy dingo-eureka repository
      run: |
        echo "Move dingo-eureka repository"
        sudo cp -r /home/runner/work/dingo-eureka/dingo-eureka /mnt/
        sudo chown -R $USER:$USER /mnt/dingo-eureka

    - name: Set Safe Dir
      run: git config --global --add safe.directory /mnt/dingo-eureka
    
    - name: Configure Docker data-root
      run: |
        sudo systemctl stop docker
        sudo systemctl stop docker.socket
        sudo mkdir -p /mnt/docker
        echo '{ "data-root": "/mnt/docker" }' | sudo tee /etc/docker/daemon.json
        if [ -d /var/lib/docker ]; then
          sudo mv /var/lib/docker /mnt/docker || true
        fi
        sudo systemctl start docker.socket
        sudo systemctl start docker
        docker info | grep "Docker Root Dir"

    - name: Sync submodules
      if: ${{ github.event_name == 'push'}}
      run: |
        cd /mnt/dingo-eureka
        git submodule sync --recursive
        git submodule update --init --recursive

    - name: Clean .git directory
      run: |
        find /mnt/dingo-eureka -name ".git" -type d -exec rm -rf {} +

    - name: Pull dingodatabase/dingo-base:rocky9
      if: ${{ github.event_name == 'push'}}
      run: |
        docker pull dingodatabase/dingo-eureka:rocky9

    - name: Set up Docker Buildx
      if: ${{ github.event_name == 'push'}}
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      if: ${{ github.event_name == 'push'}}
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push 'dingo-eureka:rocky9-fs'
      if: ${{ github.event_name == 'push'}}
      uses: docker/build-push-action@v6
      with:
        context: /mnt/dingo-eureka
        file: /mnt/dingo-eureka/docker/eureka/rocky9/Dockerfile-fs
        push: true
        tags: rocky9-fs
  